version: "3.9"  # optional since v1.27.0
services:
  web:
    container_name: 'web'
    build: ./backend
    environment:
      - SERVER_MODE=dev
      - HOST=0.0.0.0
      - PORT=8080
      - DBUSER=user
      - DBPASSWORD=pass
      - DBNAME=db
      - DBHOST=web-db
      - DBPORT=5432
      - DBSSLMODE=disable
      - QUEUE_HOST=rabbitmq
      - QUEUE_PORT=5672
      - QUEUE_USER=guest
      - QUEUE_PASS=guest
    depends_on:
      - web-db
      - rabbitmq
    links:
      - web-db
      - rabbitmq

  web-copy:
    container_name: 'web-copy'
    build: ./backend
    environment:
      - SERVER_MODE=dev
      - HOST=0.0.0.0
      - PORT=8081
      - DBUSER=user
      - DBPASSWORD=pass
      - DBNAME=db
      - DBHOST=web-db
      - DBPORT=5432
      - DBSSLMODE=disable
      - QUEUE_HOST=rabbitmq
      - QUEUE_PORT=5672
      - QUEUE_USER=guest
      - QUEUE_PASS=guest
    depends_on:
      - web-db
      - rabbitmq
    links:
      - web-db
      - rabbitmq


  consumer:
    container_name: 'consumer'
    build: ./consumer
    environment:
      - SERVER_ADDR=nginx
      - QUEUE_HOST=rabbitmq
      - QUEUE_PORT=5672
      - QUEUE_USER=guest
      - QUEUE_PASS=guest
      - CACHE_HOST=web-cache
      - CACHE_PORT=6379
    depends_on:
      - rabbitmq
      - nginx
      - web-cache
    links:
      - nginx
      - web-cache
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5

  web-db:
    container_name: 'web-db'
    image: postgres:12
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    volumes:
      - ./storage/postgresql/data:/var/lib/postgresql/data
    restart: unless-stopped

  web-cache:
    container_name: 'web-cache'
    image: "redis:alpine"
    ports:
      - "6380:6379"
    restart: unless-stopped


  nginx:
    # specifies the latest nginx image
    image: nginx:latest
    # Connects the conf file of the container to the conf file in our folder
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    # It will start up the nginx only when all api containers have started
    depends_on:
      - web
      - web-copy
    # Connects the port 80 of the nginx container to localhost:80 or localhost
    ports:
      - "80:80"
    links:
      - web
      - web-copy